# Generated by Django 2.0.3 on 2018-05-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('restrooms', 'restrooms'), ('showers', 'showers')], default='', max_length=255)),
                ('organization', models.TextField(default='', max_length=255, null=True)),
                ('website', models.TextField(default='', max_length=255, null=True)),
                ('short_description', models.TextField(default='', max_length=1000, null=True)),
                ('hours', models.TextField(default='', max_length=255, null=True)),
                ('address', models.TextField(default='', max_length=255, null=True)),
                ('phone', models.TextField(default='', max_length=255)),
                ('lat', models.TextField(default='', max_length=255)),
                ('lgn', models.TextField(default='', max_length=255)),
                ('gender', models.TextField(default='', max_length=255, null=True)),
            ],
        ),
    ]
