# Generated by Django 2.0.3 on 2018-05-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latrineapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='lgn',
            new_name='lng',
        ),
    ]
