# Generated by Django 2.0.3 on 2018-05-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latrineapp', '0002_auto_20180530_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('thumbs_up', 'thumbs_up'), ('thumbs_down', 'thumbs_down')], default='', max_length=255, null=True)),
                ('comment', models.TextField(default='', max_length=2000, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='latrineapp.Facility')),
            ],
        ),
    ]
