# Generated by Django 2.0.3 on 2018-05-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latrineapp', '0003_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(choices=[('thumbs_up', 'thumbs_up'), ('thumbs_down', 'thumbs_down')], default='', max_length=255, null=True)),
                ('comment', models.TextField(default='', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.TextField(default='', max_length=255, null=True)),
                ('website', models.TextField(default='', max_length=255, null=True)),
                ('short_description', models.TextField(default='', max_length=1000, null=True)),
                ('address', models.TextField(default='', max_length=255, null=True)),
                ('phone', models.TextField(default='', max_length=255)),
                ('lat', models.TextField(default='', max_length=255)),
                ('lng', models.TextField(default='', max_length=255)),
                ('gender', models.TextField(default='', max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(default='', max_length=255)),
                ('hours', models.TextField(default='', max_length=255, null=True)),
                ('short_description', models.TextField(default='', max_length=1000, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='latrineapp.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='flag',
            name='facility',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Flag',
        ),
        migrations.AddField(
            model_name='feedback',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='latrineapp.Resource'),
        ),
    ]
