# Generated by Django 2.0.3 on 2018-06-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latrineapp', '0005_auto_20180602_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.TextField(default='', max_length=255),
        ),
    ]
