# Generated by Django 2.0.3 on 2018-06-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latrineapp', '0007_auto_20180602_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gender',
            field=models.TextField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.TextField(default='', max_length=20, null=True),
        ),
    ]
