# Generated by Django 2.0.2 on 2018-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latrineapp', '0008_auto_20180609_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='icon_type',
        ),
        migrations.AddField(
            model_name='feedback',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='accessible',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='resource',
            name='changing_table',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
