# Generated by Django 2.0.2 on 2018-07-20 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('latrineapp', '0009_auto_20180703_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='latrineapp.Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='accessible',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='changing_table',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='latrineapp.Place'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('lat', 'lng')},
        ),
    ]
